// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_student_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_student_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_student_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_student_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_student_2eproto;
namespace student {
class Course;
struct CourseDefaultTypeInternal;
extern CourseDefaultTypeInternal _Course_default_instance_;
class StudentInfo;
struct StudentInfoDefaultTypeInternal;
extern StudentInfoDefaultTypeInternal _StudentInfo_default_instance_;
}  // namespace student
PROTOBUF_NAMESPACE_OPEN
template<> ::student::Course* Arena::CreateMaybeMessage<::student::Course>(Arena*);
template<> ::student::StudentInfo* Arena::CreateMaybeMessage<::student::StudentInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace student {

enum Sex : int {
  MALE = 0,
  FEMALE = 1,
  Sex_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Sex_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Sex_IsValid(int value);
constexpr Sex Sex_MIN = MALE;
constexpr Sex Sex_MAX = FEMALE;
constexpr int Sex_ARRAYSIZE = Sex_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Sex_descriptor();
template<typename T>
inline const std::string& Sex_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Sex>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Sex_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Sex_descriptor(), enum_t_value);
}
inline bool Sex_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Sex* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Sex>(
    Sex_descriptor(), name, value);
}
// ===================================================================

class Course final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:student.Course) */ {
 public:
  inline Course() : Course(nullptr) {}
  ~Course() override;
  explicit PROTOBUF_CONSTEXPR Course(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Course(const Course& from);
  Course(Course&& from) noexcept
    : Course() {
    *this = ::std::move(from);
  }

  inline Course& operator=(const Course& from) {
    CopyFrom(from);
    return *this;
  }
  inline Course& operator=(Course&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Course& default_instance() {
    return *internal_default_instance();
  }
  static inline const Course* internal_default_instance() {
    return reinterpret_cast<const Course*>(
               &_Course_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Course& a, Course& b) {
    a.Swap(&b);
  }
  inline void Swap(Course* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Course* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Course* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Course>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Course& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Course& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Course* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "student.Course";
  }
  protected:
  explicit Course(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kCreditFieldNumber = 1,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 credit = 1;
  void clear_credit();
  int32_t credit() const;
  void set_credit(int32_t value);
  private:
  int32_t _internal_credit() const;
  void _internal_set_credit(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:student.Course)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int32_t credit_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_student_2eproto;
};
// -------------------------------------------------------------------

class StudentInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:student.StudentInfo) */ {
 public:
  inline StudentInfo() : StudentInfo(nullptr) {}
  ~StudentInfo() override;
  explicit PROTOBUF_CONSTEXPR StudentInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StudentInfo(const StudentInfo& from);
  StudentInfo(StudentInfo&& from) noexcept
    : StudentInfo() {
    *this = ::std::move(from);
  }

  inline StudentInfo& operator=(const StudentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline StudentInfo& operator=(StudentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StudentInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const StudentInfo* internal_default_instance() {
    return reinterpret_cast<const StudentInfo*>(
               &_StudentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StudentInfo& a, StudentInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(StudentInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StudentInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StudentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StudentInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StudentInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const StudentInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StudentInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "student.StudentInfo";
  }
  protected:
  explicit StudentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCourseFieldNumber = 4,
    kNameFieldNumber = 2,
    kAgeFieldNumber = 1,
    kSexFieldNumber = 3,
  };
  // repeated .student.Course course = 4;
  int course_size() const;
  private:
  int _internal_course_size() const;
  public:
  void clear_course();
  ::student::Course* mutable_course(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::student::Course >*
      mutable_course();
  private:
  const ::student::Course& _internal_course(int index) const;
  ::student::Course* _internal_add_course();
  public:
  const ::student::Course& course(int index) const;
  ::student::Course* add_course();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::student::Course >&
      course() const;

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 1;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // .student.Sex sex = 3;
  void clear_sex();
  ::student::Sex sex() const;
  void set_sex(::student::Sex value);
  private:
  ::student::Sex _internal_sex() const;
  void _internal_set_sex(::student::Sex value);
  public:

  // @@protoc_insertion_point(class_scope:student.StudentInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::student::Course > course_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int32_t age_;
  int sex_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_student_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Course

// int32 credit = 1;
inline void Course::clear_credit() {
  credit_ = 0;
}
inline int32_t Course::_internal_credit() const {
  return credit_;
}
inline int32_t Course::credit() const {
  // @@protoc_insertion_point(field_get:student.Course.credit)
  return _internal_credit();
}
inline void Course::_internal_set_credit(int32_t value) {
  
  credit_ = value;
}
inline void Course::set_credit(int32_t value) {
  _internal_set_credit(value);
  // @@protoc_insertion_point(field_set:student.Course.credit)
}

// string name = 2;
inline void Course::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Course::name() const {
  // @@protoc_insertion_point(field_get:student.Course.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Course::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:student.Course.name)
}
inline std::string* Course::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:student.Course.name)
  return _s;
}
inline const std::string& Course::_internal_name() const {
  return name_.Get();
}
inline void Course::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* Course::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* Course::release_name() {
  // @@protoc_insertion_point(field_release:student.Course.name)
  return name_.Release();
}
inline void Course::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:student.Course.name)
}

// -------------------------------------------------------------------

// StudentInfo

// int32 age = 1;
inline void StudentInfo::clear_age() {
  age_ = 0;
}
inline int32_t StudentInfo::_internal_age() const {
  return age_;
}
inline int32_t StudentInfo::age() const {
  // @@protoc_insertion_point(field_get:student.StudentInfo.age)
  return _internal_age();
}
inline void StudentInfo::_internal_set_age(int32_t value) {
  
  age_ = value;
}
inline void StudentInfo::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:student.StudentInfo.age)
}

// string name = 2;
inline void StudentInfo::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& StudentInfo::name() const {
  // @@protoc_insertion_point(field_get:student.StudentInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StudentInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:student.StudentInfo.name)
}
inline std::string* StudentInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:student.StudentInfo.name)
  return _s;
}
inline const std::string& StudentInfo::_internal_name() const {
  return name_.Get();
}
inline void StudentInfo::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* StudentInfo::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* StudentInfo::release_name() {
  // @@protoc_insertion_point(field_release:student.StudentInfo.name)
  return name_.Release();
}
inline void StudentInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:student.StudentInfo.name)
}

// .student.Sex sex = 3;
inline void StudentInfo::clear_sex() {
  sex_ = 0;
}
inline ::student::Sex StudentInfo::_internal_sex() const {
  return static_cast< ::student::Sex >(sex_);
}
inline ::student::Sex StudentInfo::sex() const {
  // @@protoc_insertion_point(field_get:student.StudentInfo.sex)
  return _internal_sex();
}
inline void StudentInfo::_internal_set_sex(::student::Sex value) {
  
  sex_ = value;
}
inline void StudentInfo::set_sex(::student::Sex value) {
  _internal_set_sex(value);
  // @@protoc_insertion_point(field_set:student.StudentInfo.sex)
}

// repeated .student.Course course = 4;
inline int StudentInfo::_internal_course_size() const {
  return course_.size();
}
inline int StudentInfo::course_size() const {
  return _internal_course_size();
}
inline void StudentInfo::clear_course() {
  course_.Clear();
}
inline ::student::Course* StudentInfo::mutable_course(int index) {
  // @@protoc_insertion_point(field_mutable:student.StudentInfo.course)
  return course_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::student::Course >*
StudentInfo::mutable_course() {
  // @@protoc_insertion_point(field_mutable_list:student.StudentInfo.course)
  return &course_;
}
inline const ::student::Course& StudentInfo::_internal_course(int index) const {
  return course_.Get(index);
}
inline const ::student::Course& StudentInfo::course(int index) const {
  // @@protoc_insertion_point(field_get:student.StudentInfo.course)
  return _internal_course(index);
}
inline ::student::Course* StudentInfo::_internal_add_course() {
  return course_.Add();
}
inline ::student::Course* StudentInfo::add_course() {
  ::student::Course* _add = _internal_add_course();
  // @@protoc_insertion_point(field_add:student.StudentInfo.course)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::student::Course >&
StudentInfo::course() const {
  // @@protoc_insertion_point(field_list:student.StudentInfo.course)
  return course_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace student

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::student::Sex> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::student::Sex>() {
  return ::student::Sex_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_student_2eproto
